ALTER TABLE gesprev.servidor
ALTER COLUMN cpf TYPE VARCHAR(20),
ALTER COLUMN pis TYPE VARCHAR(20),
ALTER COLUMN matricula TYPE VARCHAR(30),
ALTER COLUMN email TYPE VARCHAR(120),
ALTER COLUMN cargo TYPE VARCHAR(120),
ALTER COLUMN orgao TYPE VARCHAR(160);
